[programs.localnet]
wordcel = "D9JJgeRf2rKq5LNMHLBMb92g4ZpeMgCyvZkd7QKwSCzg"
invite = "6G5x4Es2YZYB5e4QkFJN88TrfLABkYEQpkUH5Gob9Cut"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/wordcel_admin.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000"
cli = "yarn run ts-node --experimental-top-level-await -P ./tsconfig.json scripts/cli.ts"
invite = "yarn run ts-node --experimental-top-level-await -P ./tsconfig.json scripts/invite.ts"
